version: "3.11"
services:
  postgres_exporter:
    container_name: postgres_exporter
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - "5000:5000"
